//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WemaATMJournalArchhiver.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class AJ_UsersTable
    {
        public int UserID { get; set; }
        public string Username { get; set; }
        public string BranchorDepartment { get; set; }
        public string AccessType { get; set; }
        public bool UserStatus { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
