//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WemaATMJournalArchhiver.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class new_atm_log_path
    {
        public System.Guid path_id { get; set; }
        public string branch_code { get; set; }
        public string year { get; set; }
        public string filename { get; set; }
        public string new_file_path { get; set; }
        public string ipaddress { get; set; }
        public string terminalid { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
    }
}
